apiVersion: v1
kind: Service
metadata:
  name: prod-service
  labels:
    app: myapp
    
spec:
  ports:
    - name: my-app-port
      port: 8080
    

  selector:
    app: myapp

  type: LoadBalancer
            