apiVersion: apps/v1 

kind: Deployment

metadata:  
  name: prod-webapp 
  labels: 
    app: myapp 

spec: 
  replicas: 4 
  
  selector: 
    matchLabels: 
      app: myapp 

  template: 
    metadata: 
      labels: 
        app: myapp 

    spec: 
      containers: 
      - name: my-webapp 
        image: kaushik1992/image1
        imagePullPolicy: Always 
        ports:  
        - containerPort: 8080 

  strategy: 
   type: RollingUpdate 
   rollingUpdate: 
     maxSurge: 1 
     maxUnavailable: 1 